services:
  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - php-fpm
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./src:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
      args:
        - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    environment:
      PHP_IDE_CONFIG: "serverName=radstand-server"

  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/app
      - composer:/root/.composer/cache
   
  postgres:
    build:
      context: ./docker
      dockerfile: postgres/Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/app:/app
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_USER: ${POSTGRES_USER:-test_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_db_password}
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  composer:
  postgres:
